# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 174010528c0a5e9b070b4e5ba916decc83b3ca1d54214c0f4d55b6e06c29e565b6eab7dd62026d104ae9e3db192e8c9936ef6128dd2abfa4314bdc6034836ebf

test:
  secret_key_base: a81b055a537b600642f728b59973d5352224193618ddc45298ffeaa21d0c0981a8bf139c97b220cd23f2189cab004757e06112d80907f4babd229266eb7e15db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
